// Memoria justificativa que precede a la liquidación de dietas. El texto es el
// documento oficial del Servicio, ÍNTEGRO y con acentos: lo único que cambia son
// las fechas del periodo, sustituidas según el mes seleccionado.

export type BloqueMemoria =
  | { tipo: 'titulo'; texto: string }
  | { tipo: 'periodo'; texto: string }
  | { tipo: 'seccion'; texto: string }
  | { tipo: 'sub'; texto: string }
  | { tipo: 'parrafo'; texto: string }
  | { tipo: 'bullet'; texto: string }

const MESES = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']

export function fechasMemoria(mesAnio: string) {
  const [y, m] = mesAnio.split('-').map(Number)
  const ultimo = new Date(y, m, 0).getDate()
  const mm = String(m).padStart(2, '0')
  const dd = String(ultimo).padStart(2, '0')
  const mes = MESES[m - 1]
  return {
    periodoTitulo: `PERIODO DEL 01-${mm}-${y} AL ${dd}-${mm}-${y}`,
    entreLargo: `${1} de ${mes} de ${y} y el ${ultimo} de ${mes} de ${y}`,
    entreCorto: `01/${mm}/${y} y el ${dd}/${mm}/${y}`,
  }
}

export function bloquesMemoriaDietas(mesAnio: string): BloqueMemoria[] {
  const f = fechasMemoria(mesAnio)
  return [
    { tipo: 'titulo', texto: 'INFORME JUSTIFICACIÓN DE COMPENSACIÓN DE LAS DIETAS PARA LOS MIEMBROS DEL SERVICIO LOCAL DE PROTECCIÓN CIVIL' },
    { tipo: 'periodo', texto: f.periodoTitulo },

    { tipo: 'seccion', texto: 'INTRODUCCIÓN:' },
    { tipo: 'parrafo', texto: 'El presente informe tiene como objetivo justificar la compensación de las dietas para los miembros del Servicio Local de Protección Civil del Ayuntamiento de Bormujos, conforme a la legislación vigente en materia de Seguridad y Emergencias. Esta compensación responde a la necesidad de cubrir los gastos derivados de la participación de los voluntarios en actividades relacionadas con la protección, prevención e intervención en situaciones de emergencia, tal como se establece en las normativas que regulan el sistema de Protección Civil a nivel nacional, autonómico y local.' },
    { tipo: 'parrafo', texto: 'La Agrupación Local de Voluntarios de Protección Civil de Bormujos forma parte del Servicio Local de Protección Civil, conforme a la Ley 2/2002, de 11 de noviembre, de Gestión de Emergencias de Andalucía, y al Decreto 159/2016, de 4 de octubre, que regula los servicios de Protección Civil en la Comunidad Autónoma de Andalucía. Además, este servicio se rige por el Reglamento del Servicio Local de Protección Civil de Bormujos, aprobado por el Pleno Municipal en sesión ordinaria, con fecha 30 de marzo de 2020, entrando en vigor el 1 de febrero de 2021, tras su publicación en el Boletín Oficial de la Provincia (BOP). Este reglamento establece el marco normativo local para la organización, funcionamiento y responsabilidades del servicio.' },
    { tipo: 'parrafo', texto: 'La creación de este reglamento no solo permite la regulación formal de las actividades de los voluntarios, sino que también refuerza el compromiso del municipio con la protección de las personas y bienes en situaciones de emergencia. En línea con los principios de altruismo y voluntariedad que fundamentan la Protección Civil, el reglamento estipula en su Capítulo III, Artículo 11, punto 2 la obligación de la administración local de compensar los gastos que los voluntarios puedan tener durante el desempeño de sus funciones, sin que esto implique una relación laboral. Estas compensaciones incluyen los gastos derivados de desplazamientos, manutención y otros servicios necesarios para asegurar el adecuado desarrollo de sus actividades.' },
    { tipo: 'parrafo', texto: 'En los últimos años, el Ayuntamiento de Bormujos ha realizado una importante labor de modernización y mejora del Servicio Local de Protección Civil. Se han realizado inversiones en infraestructuras, equipamientos y formación para garantizar una adecuada respuesta ante emergencias. Además, el municipio cuenta con un Plan de Emergencias Municipal (PEM), cuya última actualización se encuentra en proceso, con el objetivo de mejorar la capacidad de respuesta ante situaciones de riesgo, adaptándose a los cambios en el entorno y posibles nuevas amenazas.' },
    { tipo: 'parrafo', texto: 'Con este informe, se pretende dotar de argumentos sólidos a la administración local para proceder al abono de las compensaciones por dietas, conforme a lo estipulado en la normativa vigente. Asimismo, se pone en valor el trabajo continuo de los voluntarios en la prevención y gestión de emergencias, y se refuerza la importancia de que la administración asuma su responsabilidad en cuanto a los gastos derivados de estas actividades.' },
    { tipo: 'parrafo', texto: 'El marco legal que se detalla a continuación respalda la obligación de la administración de cubrir los gastos relacionados con los servicios de Protección Civil, asegurando que los voluntarios puedan realizar sus funciones sin perjuicio económico, en cumplimiento con los principios de solidaridad y colaboración que rigen el sistema de Protección Civil.' },

    { tipo: 'seccion', texto: 'MARCO LEGAL:' },
    { tipo: 'parrafo', texto: 'El marco legal que regula la actividad de los servicios de Protección Civil es extenso, y abarca tanto legislación de ámbito nacional, autonómico y local, que en conjunto permite una adecuada regulación de su funcionamiento. A continuación, se detallan las principales leyes y disposiciones normativas que resultan de aplicación directa en la justificación de la compensación de dietas para los miembros del Servicio Local de Protección Civil del Ayuntamiento de Bormujos:' },
    { tipo: 'sub', texto: '1. Ámbito Nacional:' },
    { tipo: 'bullet', texto: 'Ley 17/2015, de 9 de julio, del Sistema Nacional de Protección Civil: Esta ley constituye el principal marco normativo en el ámbito de la Protección Civil en España. Reemplaza la Ley 2/1985, modernizando y reforzando los principios de actuación del Sistema Nacional de Protección Civil. En ella se establece un sistema integral de prevención, planificación, respuesta y rehabilitación ante situaciones de emergencia, basándose en los principios de coordinación entre las diferentes administraciones públicas. Además, se reconoce la importancia de la colaboración entre los diferentes servicios de intervención y emergencia, incluyendo a los servicios locales de Protección Civil, como el de Bormujos. Esta ley refuerza la importancia de la planificación preventiva y la gestión de riesgos, así como la actuación rápida y coordinada ante emergencias que puedan afectar tanto a las personas como a los bienes.' },
    { tipo: 'bullet', texto: 'Real Decreto 462/2002, de 24 de mayo, sobre indemnizaciones por razón del servicio: Esta norma regula el régimen de indemnizaciones por razón del servicio, incluyendo el derecho a dietas, compensaciones por desplazamientos, manutención y alojamiento para quienes presten servicio en nombre de la administración pública. Aunque no establece una relación laboral, permite que los voluntarios de Protección Civil, en su calidad de colaboradores con la administración, reciban una compensación económica que cubra los gastos ocasionados durante la prestación del servicio, sin que esto altere el carácter voluntario de su labor.' },
    { tipo: 'bullet', texto: 'Ley 7/1985, de 2 de abril, Reguladora de las Bases del Régimen Local (LBRL): Esta ley define las competencias municipales, incluyendo aquellas en materia de Protección Civil. En sus artículos 25 y 26 se establece que los municipios tienen la competencia para llevar a cabo actividades relacionadas con la protección de las personas y bienes en situaciones de emergencia o catástrofe. En el caso de municipios con más de 20.000 habitantes, como es el caso de Bormujos, la ley impone la obligación de contar con servicios adecuados de Protección Civil para asegurar una respuesta eficaz ante riesgos locales. De igual manera, esta norma permite que el Ayuntamiento estructure y regule la compensación de gastos para los voluntarios que participan en tareas de prevención y gestión de emergencias.' },
    { tipo: 'bullet', texto: 'Real Decreto 393/2007, de 23 de marzo, por el que se aprueba la Norma Básica de Autoprotección: Esta disposición establece los requisitos mínimos que deben cumplirse para garantizar la autoprotección de personas y bienes en situaciones de emergencia. La Norma Básica de Autoprotección exige la adopción de planes de actuación por parte de entidades públicas y privadas para hacer frente a emergencias, reforzando el papel de los servicios locales de Protección Civil en la coordinación y ejecución de dichos planes.' },
    { tipo: 'sub', texto: '2. Ámbito Autonómico:' },
    { tipo: 'bullet', texto: 'Ley 2/2002, de 11 de noviembre, de Gestión de Emergencias en Andalucía: Esta ley establece el marco regulador de la protección de personas, bienes y medio ambiente en situaciones de emergencia dentro de la Comunidad Autónoma de Andalucía. Reconoce la importancia de la coordinación entre las administraciones públicas y la integración de todos los recursos disponibles para la gestión de emergencias. En este contexto, se otorga un papel relevante a los municipios en la planificación y ejecución de planes de emergencia, así como en la prevención de riesgos. La ley contempla la posibilidad de que los voluntarios de Protección Civil reciban compensación por los gastos que puedan incurrir en el desempeño de sus funciones, reafirmando el carácter altruista de su labor, pero garantizando que esta no genere costes personales para los voluntarios.' },
    { tipo: 'bullet', texto: 'Decreto 159/2016, de 4 de octubre, por el que se aprueba el Reglamento General de los Servicios de Protección Civil en Andalucía: Este decreto regula la organización y el funcionamiento de los servicios de Protección Civil a nivel autonómico, y establece la estructura y funciones de los mismos. El artículo 11.2 del reglamento señala expresamente que las administraciones locales están obligadas a compensar los gastos en los que incurran los voluntarios durante la prestación de sus servicios. Asimismo, el decreto reafirma la importancia de la formación y preparación continua de los voluntarios para enfrentar situaciones de emergencia de manera eficiente.' },
    { tipo: 'sub', texto: '3. Ámbito Local:' },
    { tipo: 'bullet', texto: 'Plan de Emergencias Municipal (PEM) de Bormujos: El Plan de Emergencias Municipal es el principal instrumento de planificación y gestión de riesgos a nivel local. Se trata de un documento que establece las líneas estratégicas para la actuación en situaciones de emergencia en el municipio, contemplando tanto la prevención como la respuesta operativa ante incidentes. El PEM se actualiza regularmente para adaptarse a los cambios en el entorno y las posibles amenazas emergentes, asegurando que el Servicio Local de Protección Civil cuente con las herramientas necesarias para actuar con rapidez y eficacia en la protección de la población y los bienes municipales. La dotación de recursos humanos y materiales en el marco del PEM, junto con las actividades de formación y simulacros, refuerzan la capacidad de intervención del Servicio Local de Protección Civil.' },
    { tipo: 'bullet', texto: 'Reglamento del Servicio Local de Protección Civil de Bormujos: Aprobado por el Pleno Municipal, este reglamento define las funciones, derechos y deberes de los miembros del Servicio Local de Protección Civil, incluyendo las compensaciones económicas para los gastos derivados de su participación en las actividades del servicio. El reglamento se alinea con la normativa autonómica y nacional, asegurando que los voluntarios puedan desempeñar sus funciones sin cargas económicas, preservando el carácter voluntario y altruista de su labor.' },
    { tipo: 'parrafo', texto: 'El marco legal que regula el funcionamiento del Servicio Local de Protección Civil del Ayuntamiento de Bormujos incluye el Reglamento de la Agrupación Local de Voluntarios de Protección Civil, aprobado en sesión plenaria por unanimidad el 30 de marzo de 2020. Tras completar los trámites administrativos correspondientes, incluyendo su publicación en el Boletín Oficial de la Provincia (BOP), este reglamento entró en vigor el 1 de febrero de 2021, conforme a la diligencia emitida por la Secretaría del Ayuntamiento.' },
    { tipo: 'parrafo', texto: 'Este reglamento, basado en el Decreto 159/2016, de 4 de octubre, establece las normas que rigen la organización, funcionamiento y responsabilidades de los miembros de la agrupación. Entre otras disposiciones, el reglamento destaca en su Capítulo III, Artículo 11, punto 2 la obligación de la administración local de compensar las dietas por los gastos en los que incurran los voluntarios en el desarrollo de sus actividades. Este artículo deja claro que estas compensaciones no generan, en ningún caso, una relación laboral entre los voluntarios y la administración, manteniendo así el principio de voluntariedad y altruismo que caracteriza a la Protección Civil.' },
    { tipo: 'parrafo', texto: 'Por tanto, la aprobación de este reglamento constituye un hito en la consolidación del servicio en el municipio, al proporcionar un marco normativo que garantiza la cobertura de los gastos derivados de las funciones de los voluntarios, asegurando su operatividad y el cumplimiento de los principios de protección y seguridad en el ámbito local.' },

    { tipo: 'seccion', texto: 'JUSTIFICACIÓN DETALLADA DEL PERIODO:' },
    { tipo: 'parrafo', texto: 'El Servicio Local de Protección Civil del Ayuntamiento de Bormujos ha experimentado un crecimiento progresivo y exponencial desde finales de 2019 y principios de 2020 hasta la fecha actual, consolidándose como un pilar fundamental en la prevención y gestión de emergencias en el municipio. Este crecimiento ha sido posible gracias a las notables inversiones realizadas por la Administración Local, que ha destinado recursos tanto a la adquisición de material logístico y operativo como a la formación continua de sus miembros. Estas inversiones han permitido mejorar la capacidad de respuesta del servicio, incrementando su efectividad en situaciones de emergencia y fortaleciendo su infraestructura.' },
    { tipo: 'parrafo', texto: 'Las labores del Servicio Local de Protección Civil se estructuran en tres ejes principales: prevención, formación e intervención operativa. En primer lugar, se pone un énfasis especial en la prevención, uno de los principios fundamentales de la Protección Civil. Los miembros del servicio se encargan de estudiar y planificar los riesgos potenciales que puedan afectar al municipio, desarrollando protocolos y medidas para mitigar o reducir el impacto de estos riesgos. Este trabajo de prevención incluye la identificación de áreas vulnerables, la planificación de recursos y la colaboración con otras áreas municipales para crear un entorno más seguro para la población.' },
    { tipo: 'parrafo', texto: 'En cuanto a la formación, los voluntarios participan en un calendario formativo diseñado por el Servicio de Protección Civil, en el que se actualizan constantemente los conocimientos y habilidades necesarias para hacer frente a situaciones de emergencia. Esta formación incluye simulacros, prácticas diarias y el estudio de escenarios de riesgo, garantizando que los miembros del servicio estén preparados para intervenir de manera rápida y eficiente en cualquier situación. Además, se fomenta la colaboración y coordinación con otros servicios de emergencia, como la Policía Local, lo que permite una mayor efectividad en la gestión de incidentes.' },
    { tipo: 'parrafo', texto: 'Sin embargo, pese a los esfuerzos preventivos, no siempre es posible evitar que se produzcan situaciones de emergencia. En estos casos, y ante el fracaso de las medidas preventivas, el Servicio de Protección Civil actúa como primer interviniente, en colaboración directa con la Policía Local, ante la ausencia de servicios profesionales de emergencia y/o en espera de su llegada. Este papel como primer recurso disponible es crucial, ya que permite una primera respuesta rápida, minimizando los posibles daños a personas y bienes. Las intervenciones operativas de los miembros del servicio incluyen desde la asistencia en accidentes de tráfico y la coordinación en eventos multitudinarios, hasta el apoyo en situaciones de emergencias meteorológicas o incendios.' },
    { tipo: 'parrafo', texto: `Durante el periodo comprendido entre el ${f.entreLargo}, se han realizado numerosos servicios tanto ordinarios como extraordinarios, incluidos los correspondientes a las activaciones de emergencias, cubriendo diferentes franjas horarias. Los miembros del Servicio Local de Protección Civil han trabajado de manera organizada mediante cuadrantes de servicio presenciales, distribuidos en turnos de 09:00 a 15:00 y de 16:00 a 22:00 con carácter ordinario, con el fin de garantizar una cobertura efectiva durante la mayor parte del día. En estos turnos, además de las tareas operativas de intervención, los voluntarios han llevado a cabo labores de estudio y planificación de riesgos, prácticas diarias y la atención al sistema de emergencias 112, a través de los terminales instalados en la sede de Protección Civil, optimizando los recursos humanos y evitando la duplicidad de funciones.` },
    { tipo: 'parrafo', texto: 'Asimismo se han cubierto de forma extraordinarias todos los eventos y servicios que se han requerido para garantizar la seguridad en el desarrollo de los mismos. Este despliegue de recursos ha sido vital en las numerosas intervenciones de apoyo a la Policía Local, que ha contado con la colaboración del Servicio de Protección Civil en situaciones de emergencia como accidentes de tráfico, eventos multitudinarios y atenciones sanitarias iniciales de SVB. Además, se han llevado a cabo labores de prevención en eventos organizados por el Ayuntamiento, garantizando la seguridad de los asistentes y apoyando a otros servicios municipales cuando ha sido necesario.' },
    { tipo: 'parrafo', texto: 'El Centro de Coordinación Operativa Local (CECOPAL), también se ha convertido en un elemento clave dentro del servicio, desde donde se gestionan las incidencias y emergencias locales. A lo largo del periodo analizado, el CECOPAL ha coordinado varias actuaciones de emergencia, destacando su capacidad para gestionar de manera eficaz la entrada de avisos desde la plataforma del 112, lo que ha permitido una respuesta inmediata y coordinada con otros servicios de emergencia.' },
    { tipo: 'parrafo', texto: 'En conclusión, el Servicio Local de Protección Civil de Bormujos ha demostrado su capacidad para intervenir de manera efectiva en situaciones de emergencia, cubriendo de forma eficiente la carencia o tardanza de otros servicios profesionales, y prestando un apoyo vital a la Policía Local. Estas labores, que se desarrollan bajo el principio de voluntariedad, requieren la compensación de las dietas correspondientes, conforme a lo establecido en el reglamento aprobado en pleno, para garantizar la sostenibilidad del servicio y asegurar que los voluntarios puedan seguir desempeñando sus funciones sin que esto les suponga un perjuicio económico.' },
    { tipo: 'parrafo', texto: `Se adjunta a continuación la relación de asistencias de los miembros del Servicio Local de Protección Civil de Bormujos en el periodo comprendido entre el ${f.entreCorto}, desglosado por días, horas y turnos, con el detalle de nombre y apellidos, DNI, IBAN, y los cálculos de las compensaciones en función de las asistencias realizadas, conforme al reglamento de la agrupación.` },
    { tipo: 'parrafo', texto: 'El cálculo de los importes correspondientes a las dietas se lleva a cabo conforme al Reglamento de la Agrupación, aprobado por unanimidad en el Pleno de la Corporación. Dicho reglamento recoge en su Capítulo III, Artículo 11, apartado 2, las disposiciones relativas a la compensación por gastos derivados de los servicios prestados. Cabe destacar que, en el caso de los voluntarios residentes en Bormujos, no se contempla indemnización por concepto de desplazamiento.' },
    { tipo: 'parrafo', texto: 'Las tablas que se adjuntan a este informe presentan de manera detallada todos los datos acordados con el Sr. Interventor, necesarios para la adecuada justificación del abono de las indemnizaciones por dietas y, en su caso, desplazamientos. Esta información ha sido recopilada minuciosamente para asegurar la total transparencia y claridad en la justificación de los pagos correspondientes.' },

    { tipo: 'seccion', texto: 'ANEXO I: ACUERDOS INDIVIDUALES' },
    { tipo: 'parrafo', texto: 'Es fundamental destacar el principio de altruismo y gratuidad que rige a los Servicios de Protección Civil. Sin embargo, también es imprescindible reconocer el marco legal que establece claramente la obligación de las administraciones en cuanto al pago de las dietas derivadas de los servicios prestados por Protección Civil, siendo su responsabilidad directa.' },
    { tipo: 'parrafo', texto: 'Por tanto, resulta igualmente importante dejar claro que, en ningún caso, se entiende la existencia de una relación laboral entre los miembros del Servicio y la Administración Local.' },
    { tipo: 'parrafo', texto: 'Se ha elaborado un acuerdo individual entre cada miembro del servicio y la administración local, firmado libremente por ambas partes, en el que se reconocen sus derechos y obligaciones, tanto presentes como futuras, para que surta los efectos correspondientes.' },
    { tipo: 'parrafo', texto: 'Al presente informe se adjuntan los acuerdos individuales, que serán entregados de forma exclusiva, salvo que en el futuro se integren nuevos miembros al servicio, lo cual conllevará la incorporación de los acuerdos individuales correspondientes.' },
  ]
}
